version: "3.9"
services:
  tailwindcss:
    build:
      context: .
      dockerfile: Dockerfile.build
    volumes:
      - ./docs:/app/src
      - ./dist:/app/dist
      - ./tailwind.config.js:/app/tailwind.config.js
    command: ["sh", "-c", "while true; do npx tailwindcss -i ./src/input.css -o ./dist/output.css > /dev/null 2>&1; sleep 1; done"]

